apiVersion: v1
kind: ConfigMap
metadata:
  name: am-demo
data:
  config.yaml: |
    alertmanager:
      servers:
        - name: am1
          uri: http://prometheus-kube-prometheus-alertmanager.monitoring.svc:9093/
        - name: am2
          uri: http://prom-stand-by-kube-prometh-alertmanager.demo.svc:9093/
---
apiVersion: v1
kind: Service
metadata:
  name: am
spec:
  selector:
    app: am
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: am
  labels:
    app: am
spec:
  replicas: 1
  selector:
    matchLabels:
      app: am
  template:
    metadata:
      labels:
        app: am
    spec:
      containers:
      - name: am
        image: ghcr.io/prymitive/karma:latest
        ports:
        - containerPort: 8080
        args:
        - --config.file=config/config.yaml
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: am-demo
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "config.yaml"
              path: "config.yaml"
