apiVersion: v1
kind: Service
metadata:
  name: am
spec:
  selector:
    app: am
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: am
  labels:
    app: am
spec:
  replicas: 1
  selector:
    matchLabels:
      app: am
  template:
    metadata:
      labels:
        app: am
    spec:
      containers:
      - name: am
        image: ghcr.io/prymitive/karma:latest
        ports:
        - containerPort: 8080
        args:
        - --alertmanager.uri=http://prometheus-kube-prometheus-alertmanager.monitoring.svc:9093
